# Site settings
title: ML's Blog
SEOTitle: ML | Your Blog
header-img: /img/home-bg.jpg
email: mml2015@126.com
description: "我的GitHub博客"
keyword: "GitHub,博客"
url:  "https://mamenglong.github.io/"              # your host, for absolute URL
# url:   "http://127.0.0.1:4000/"
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'
# jekyll serve -w

# Publish posts or collection documents with a future date.
future: true
# SNS settings
RSS: false
# weibo_username:
# zhihu_username:
github_username:    mamenglong
csdn_username:      smallbabylong
#twitter_username:
# facebook_username:



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
#Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  extensions:
    - autolink
    - footnotes
    - smart
  #  coderay_default_lang: java    #设置突出显示代码块的默认语言
  #  coderay_line_number_start: 1  # 行号的起始值
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
# duoshuo_username:  
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: longloveyue.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写Bug,看看你。"
sidebar-avatar: /img/avatar.gif      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

# share me by qr code
shareme: true   #  false

# Friends
friends: [
    {
        title: "CSDN Blog",
        href: "https://blog.csdn.net/smallbabylong"
    },{
        title: "Foo",
        href: "#"
    },{
        title: "Bar",
        href: "#"
    },{
        title: "Example Friends",
        href: "#"
    },{
        title: "It helps SEO",
        href: "#"
    }
]
